### ISSUE TITLE
402 error

### ISSUE THREAD

**Issue by feralheart** [filippotoso/qwant-unofficial-api#2]
Thank you for your work.

I got 402 error:
`GET https:\/\/api.qwant.com\/api\/search\/web?count=10&offset=0&q=marketing&t=all&device=desktop&safesearch=1&locale=en_US` resulted in a `402 Payment Required` response:\n{\"status\":\"success\",\"data\":{\"result\":{\"items\":[]},\"error_code\":9}}\n" `

**Comment by filippotoso** [comment]
Fixed in 1.0.2
